HTML form page
Audrey-Ella-xo/HTML-Forms pull request #1
Opened 2019-09-19 22:45 UTC by Audrey-Ella-xo

We created a replica of mint.com's sign up page. we:

- Designed the form in html and css

- Added Header and footer elements

- Added linters to our project

2019-09-20 10:52 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-09-20 11:47 UTC, Torres-ssf requested changes
### Hi there team :hand: 
Nicely done with this project, it's looking really nice :tada: :clap: 

### However, there are some changes needed to be made before merging to master.

- [x] You need to fix the all errors found by the linter. Linting is important to reduce errors and improve the overall quality of your code :smiley: . 

- [x] Instead, to use only one image for all logos, you need to use 4 separate images for each logo and use text for the name of the 3 products (mint, quickbooks, turbotax)

Please kindly make these changes and submit for code review again. :computer: 

**[FOR FUTURE PROJECTS]**
Nice job not naming the branch of dev/developer. But next time try to give a feature name for the branch(e.g. 'created-form'), just like it said in the Github flow [instructions](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/)

2019-09-20 11:47 UTC, Torres-ssf commented on index.html
> +                    <img src="http://i.imgur.com/jnYFslI.png" alt="intuit_logo"/>
Use 4 separate images for each logo and use text for the name of the 3 products (mint, quickbooks, turbotax)

2019-09-20 21:57 UTC, Audrey-Ella-xo commented on index.html
> +                    <img src="http://i.imgur.com/jnYFslI.png" alt="intuit_logo"/>
All linter errors have been fixed
The images have been added

2019-09-20 22:12 UTC, Audrey-Ella-xo commented
Fixed issues as per feedback

2019-09-21 20:30 UTC, Forison reviewed
# pull request under review by Addo

2019-09-21 20:35 UTC, Forison approved these changes
# Bravo Team👋👋
You have done an 👌 job. Project is **[approved]**, go ahead and merge to master. 
Proceed to the next project.
#### Happy coding 🙂

2019-09-21 20:35 UTC, bolah2009 approved these changes
## Nice job with the [clone](https://raw.githack.com/Audrey-Ella-xo/HTML-Forms/0639ba0a2ffe6d1ad043f265d4b345f50de80cbd/index.html). :ok_hand: 

Uses HTML form elements and attributes effectively. :clap: 

### It's a :+1: from me. You can merge to master.

2019-09-21 20:35 UTC, bolah2009 commented on README.md
> + * [Odiaka Emmanuella Anita](https://github.com/Audrey-Ella-xo)
Let's make the `README` file more descriptive, details like what was done in the projects, what was learned, link to the assignment, clone and source page, screenshots of the clone page can make README look more professional.
 > Remember about descriptive README file.

2019-09-21 20:35 UTC, bolah2009 commented on index.html
> +                    <img src="http://i.imgur.com/0S2xUrj.png" alt="intuit_logo"/>
Use `https` instead of `http`, this makes websites more secure. [Learn more here](https://support.google.com/chrome/?p=ui_security_indicator)

2019-09-21 20:35 UTC, bolah2009 commented on index.html
> +            <input type="email" name="email" id="email" required>
####  `AWESOME`

Good job nesting `<input>` element inside the `<label>` element. :clap: :+1: 

> #### Associating a `<label>` with an `<input>` element offers some major advantages:
> 
> - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> 
> - You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

You can learn more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

2019-09-23 15:40 UTC, rna commented on README.md
> + * [Odiaka Emmanuella Anita](https://github.com/Audrey-Ella-xo)
Fixed as per suggestion.

2019-09-23 15:40 UTC, rna commented on index.html
> +                    <img src="http://i.imgur.com/0S2xUrj.png" alt="intuit_logo"/>
Fixed as per suggestion.

2019-09-23 15:41 UTC, rna commented on index.html
> +            <input type="email" name="email" id="email" required>
Thanks for the encouragement.

2019-09-23 15:42 UTC, merged